version: '3'
services:
  redis:
    image: redis
    volumes:
      - bbs-redis:/data
    networks:
      - docker-bbs
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass 16051223
  mysql:
    image: mysql
    volumes:
      - bbs-mysql:/var/lib/mysql
      - ./conf.d/mysql:/etc/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
      - MYSQL_DATABASE=sceley_bbs
    networks:
      - docker-bbs
    ports:
      - 3306:3306

volumes:
  bbs-redis:
  bbs-mysql:

networks:
  docker-bbs:
    driver: bridge 