version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=16051223
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=16051223
      - MYSQL_DATABASE=sceley-bbs
    depends_on:
      - redis
      - mysql
    networks:
      - docker-bbs
    ports:
      - 80:80

  redis:
    image: redis
    volumes:
      - bbs-redis:/data
    networks:
      - docker-bbs
    command: redis-server --appendonly yes --requirepass 16051223

  mysql:
    image: mysql
    volumes:
      - bbs-mysql:/var/lib/mysql
      - ./conf.d/mysql:/etc/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
      - MYSQL_DATABASE=sceley-bbs
    networks:
      - docker-bbs
    ports:
      - 3306:3306

volumes:
  bbs-redis:
  bbs-mysql:

networks:
  docker-bbs:
    driver: bridge 