version: '2'
services:
  mysql:
    image: mysql
    expose:
      - '3306'
    volumes:
      - '$PWD/conf/mysql:/etc/mysql'
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
    container_name: mysql_bbs
  redis:
    image: redis
    expose:
      - '6379'
    container_name: redis_bbs
    command: redis-server --appendonly yes
  node:
    image: node:8.11.1
    volumes: 
      - '$PWD:/home/bbs'
    links:
      - mysql:localhost
      - redis:localhost
    ports: 
      - '8080:8080'
    container_name: node_bbs
    command: bash -c "cd /home/bbs && npm install && node app.js"