version: '2'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - '$PWD/conf.d/mysql:/etc/mysql'
    environment: 
      - MYSQL_ROOT_PASSWORD=16051223
      - MYSQL_DATABASE=bbs
    container_name: mysql_bbs
  redis:
    image: redis
    ports: 
      - '6379:6379'
    container_name: redis_bbs
    command: redis-server --appendonly yes